### ISSUE TITLE
docker run error

### ISSUE THREAD

**Issue by hsang** [neelkamath/spacy-server#38]
Hello,

First of all thank you for your excellent work, I think spacy-server is fantastic. 

I am newbie in Docker so maybe I did something wrong but I am not able tu run spacy-server. I installed Docker on my linux machine following [these instructions](https://docs.docker.com/engine/install/ubuntu/).  After that, I tried to run spacy-server and I got the following response:

`sudo docker run --rm -dp 8080:8080 neelkamath/spacy-server:latest`
`Unable to find image 'neelkamath/spacy-server:latest' locally`
`docker: Error response from daemon: manifest for neelkamath/spacy-server:latest not found: manifest unknown: manifest unknown.`
`See 'docker run --help'.`

I googled it but I didn't find anything usefull at all.

Any ideas?

Best,
Hugo

**Comment by neelkamath** [comment]
No problem.

In the [README](https://github.com/neelkamath/spacy-server/blob/master/README.md), the **Usage** section links to the project's [Docker Hub page](https://hub.docker.com/r/neelkamath/spacy-server) which gives the example command `docker run --rm -p 8000:8000 neelkamath/spacy-server:<VERSION>-<MODEL><SENSE2VEC>`. For example, you could run `docker run --rm -p 8000:8000 neelkamath/spacy-server:2-en_core_web_sm-sense2vec`.

The error you're facing arises from attempting to use the `latest` version of spaCy Server but there is no version named _latest_. The full list of versions can be found in the [tags page](https://hub.docker.com/r/neelkamath/spacy-server/tags).

**Comment by hsang** [comment]
Thank you very much, `<VERSION>-<MODEL><SENSE2VEC>` was the key.
