### ISSUE TITLE
Use Python's `from .. import ..` instead of just `import ..` for readability

### ISSUE THREAD

**Issue by neelkamath** [neelkamath/spacy-server#39]
Currently, the code looks like:

```python3
import dataclasses

@dataclasses.dataclass
class BuiltEntity:
    text: str
```

but we want it to look like:

```python3
from dataclasses import dataclass

@dataclass
class BuiltEntity:
    text: str
```

In certain places, using `from .. import ..` may be less readable, so just do what feels right!

**Comment by PabloCorbCon** [comment]
I would like to contribute to this issue since I really like your project. Is there a specific package that you don't want to change the import syntax for?

**Comment by neelkamath** [comment]
Nothing in particular. Everyone has their own idea of what is more readable, and people's own ideas change quickly (e.g., a few months ago I didn't like using `from .. import ..` but now I do). The general rule of thumb is to use `from .. import ..` when the namespace is redundant (e.g., the `dataclasses` namespace is unnecessary for `@dataclasses.dataclass`).

**Comment by PabloCorbCon** [comment]
@isamuel I think that @neelkamath wants direct imports from all the packages, not just dataclass. Correct me if i'm wrong.

**Comment by imsamuel** [comment]
> @isamuel I think that @neelkamath wants direct imports from all the packages, not just dataclass. Correct me if i'm wrong.

Thank you!
