### ISSUE TITLE
Failed to connect to localhost port 8000: Connection refused

### ISSUE THREAD

**Issue by vr0nsky** [neelkamath/spacy-server#41]
Hi, i ru the image:

docker run -d neelkamath/spacy-server:2-fr_core_news_sm

then checked:

docker ps
CONTAINER ID        IMAGE                                       COMMAND                  CREATED             STATUS                   PORTS               NAMES
1275f2eb82ec        neelkamath/spacy-server:2-fr_core_news_sm   "uvicorn src.main:ap…"   5 minutes ago       Up 5 minutes (healthy)   8000/tcp            recursing_black

But:

curl http://localhost:8000/ner -H 'Content-Type: application/json' -d '{"sections": ["My name is John Doe. I grew up in California."]}'
curl: (7) Failed to connect to localhost port 8000: Connection refused

**Comment by neelkamath** [comment]
Your command is _almost_ right. As shown in the docs, you should bind the port with `-p 8000:8000` like:
`docker run -dp 8000:8000 neelkamath/spacy-server:2-fr_core_news_sm`

Then you should be able to run the same `curl` command to get output like:
```
{
  "data": [
    {
      "text": "My name is John Doe.",
      "entities": [
        {
          "text": "John Doe",
          "label": "PER",
          "start_char": 11,
          "end_char": 19,
          "lemma": "John Doe",
          "start": 3,
          "end": 5,
          "text_with_ws": "John Doe",
          "sense2vec": []
        }
      ]
    },
    {
      "text": "I",
      "entities": []
    },
    {
      "text": "grew",
      "entities": []
    },
    {
      "text": "up in California.",
      "entities": []
    }
  ]
}
```

Feel free to reopen the issue if this didn't solve your problem.
