### ISSUE TITLE
Error response from daemon: manifest for neelkamath/spacy-server:latest

### ISSUE THREAD

**Issue by ThiagoSousa** [neelkamath/spacy-server#42]
Hey neelkamath, I tried to pull your docker using the command below, but I get the error "_Error response from daemon: manifest for neelkamath/spacy-server:latest not found: manifest unknown: manifest unknown_". Is there something going on with docker hub? Or am I doing something wrong?

`docker pull neelkamath/spacy-server`

**Comment by neelkamath** [comment]
Please see #38.
