### ISSUE TITLE
Update spaCy version

### ISSUE THREAD

**Issue by neelkamath** [neelkamath/spacy-server#45]
Update the spaCy dependency to the latest stable version:
1. Update [`requirements.txt`](https://github.com/neelkamath/spacy-server/blob/master/requirements.txt#L3).
2. Run the tests to ensure everything still works fine, and fix anything that broke. Since some of the tests match the output of the program to [hardcoded JSON files](https://github.com/neelkamath/spacy-server/tree/master/src/outputs), you can update the JSON files for the new outputs using your judgement.

If you'd like to work on this, leave a comment saying something like "I'll work on this.", and you can begin without waiting for me to OK it. The point of writing the comment is to let others know that this issue has already been taken up.

**Comment by Kishore-abhimanyu** [comment]
Can you assign me on this?
