### ISSUE TITLE
Update the dependencies used to the latest stable versions

### ISSUE THREAD

**Issue by neelkamath** [neelkamath/spacy-server#47]
1. Update the `sense2vec`, `ujson`, `uvicorn`, `pytest`, and `requests` dependencies in [`requirements.txt`](https://github.com/neelkamath/spacy-server/blob/master/requirements.txt) to the latest stable versions.
2. Run the tests to ensure everything works as expected, and fix anything that broke.

If you'd like to work on this, leave a comment saying something like "I'll work on this.", and you can begin without waiting for me to OK it. The point of writing the comment is to let others know that this issue has already been taken up.

**Comment by ry-v1** [comment]
I'll work on this.

**Comment by ry-v1** [comment]
@neelkamath - sense2vec latest version(2.0.0) latest version is compatible only with spaCy V3. Do we need bump up spaCy too?

**Comment by neelkamath** [comment]
We'll need to wait for #45 to be resolved first then.

**Comment by neelkamath** [comment]
The issue has been resolved. Remember to update the link to the sense2vec file in the [docs](https://github.com/neelkamath/spacy-server/blob/master/docs/CONTRIBUTING.md?plain=1#L12).

**Comment by ry-v1** [comment]
Submitted pull request #51.

**Comment by ry-v1** [comment]
> The issue has been resolved. Remember to update the link to the sense2vec file in the [docs](https://github.com/neelkamath/spacy-server/blob/master/docs/CONTRIBUTING.md?plain=1#L12).

sense2vec file is still at the same link. There is no updated links in the latest version.
